trigger:
- master
stages:
  - stage: RunSOOS
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: SOOSSca
        workspace:
          clean: all
        steps:
          - task: SOOS-Security-Analysis@0
            displayName: 'SOOS SCA'
            inputs:
              apiKey: 'ZjZkNzg2YzYtZGJjOC00MWViLTk5Y2UtZGNhMGQxNWJkZWIx'
              clientId: '5ae371h0d'
              projectName: '$(projectName)'
              buildVersion: '$(buildVersion)'
